language: csharp
solution: PingMyNetwork.sln
install:
  - nuget restore PingMyNetwork.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release PingMyNetwork.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./PingMyNetwork/bin/Release/PingMyNetwork.dll
